use_frameworks!

platform :ios, '8.0'

target 'JFMFramework_Example' do
  pod 'JFMFramework', :path => '../'

  target 'JFMFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
